1. You are given a matrix of random numbers, you need to output the matrix where odd rows are swapped with even rows in the original matrix.

In [4]:
import numpy as np

def swap_rows(mtx):
    # find the number of rows and columns.
    num_rows = mtx.shape[0]
    # define a new matrix to put the swapped rows in. note that this isn't a numpy array, but a regular list.
    swapped_mtx = []
    # swap each odd row with the succeeding even row.
    for i in range(0,num_rows-1,2):
        swapped_mtx.append(mtx[i+1])
        swapped_mtx.append(mtx[i])
    # if there was an odd number of rows, the last row won't have another row to swap with and may get left off
    #   the final swapped matrix-- avoid this by adding the last row automatically when there's an odd amount of rows.
    if ((num_rows % 2) != 0):
        swapped_mtx.append(mtx[-1])
    # convert the list into a numpy array.
    s_mtx = np.array(swapped_mtx)
    return s_mtx

mtx = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Original matrix was:\n {mtx}\n")
print(f"Swapped matrix is:\n {swap_rows(mtx)}")


Original matrix was:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Swapped matrix is:
 [[4 5 6]
 [1 2 3]
 [7 8 9]]


2. You are given a matrix of random numbers, you need to find the number of the column which has the biggest number

In [45]:
import numpy as np

def biggest_num(mtx):
    # find the number of rows and columns.
    num_rows = mtx.shape[0]
    num_cols = mtx.shape[1]
    # set the max_num immediately to be equal to the value of the first cell in the matrix.
    max_num = mtx[0][0]
    col_nums = []
    # loop through the matrix to find the largest number.
    for i in range(num_rows):
        for j in range(num_cols):
            if (mtx[i][j] >= max_num):
                max_num = mtx[i][j]
    
    # loop through the matrix again to record the column number of each appearance of the max. number.
    #   add "+1" to the column number because the loop begins at 0, but intuitively, we count the columns
    #   starting at 1 from the leftmost side.
    for i in range(num_rows):
        for j in range(num_cols):
            if (mtx[i][j] == max_num):
                col_nums.append(j+1)

    # turn the list into a dictionary to remove any repeated columns (dictionaries can't contain repeated keys).
    col_nums = list(dict.fromkeys(col_nums))

    results = [max_num, col_nums]
    
    return results

mtx = np.array([[11,2,1],[11,11,11],[6,4,2]])
print(f"The original matrix was:\n {mtx}")
results = biggest_num(mtx)
max_num = results[0]
col_num = results[1]

if (len(col_num) == 1):
    print(f"The largest number was {max_num}, and it was found in column {col_num}.")
elif (len(col_num) == 2):
    print(f"The largest number was {max_num}, and it was found in columns {col_num[0]} and {col_num[1]}.")
else:
    # 'end = "", flush = True' removes the automatic newline that gets printed after a string.
    # the flush() method clears the internal buffer of the file
    # the print() function comes with a parameter called end which is defaulted to print a newline
    #    after a string. forcing this parameter to an empty string removes the newline.
    print(f"The largest number was {max_num}, and it was found in columns ", end = "")
    for i in range(len(col_num)-1):
        print(str(col_num[i]) + ", ", end = "")
    print(f"and {col_num[-1]}.")

The original matrix was:
 [[11  2  1]
 [11 11 11]
 [ 6  4  2]]
The largest number was 11, and it was found in columns 1, 2, and 3.


3. You are given a matrix of random numbers, you need to find the number of the column which has the biggest sum of numbers.

In [62]:
import numpy as np

def biggest_sum(mtx):
    # find the number of rows and columns.
    num_rows = mtx.shape[0]
    num_cols = mtx.shape[1]

    sum = 0
    sum_list = []
    # loop through each column to find the sum of them, and add them to a list.
    for i in range(num_cols):
        for j in range(num_rows):
            sum = sum + mtx[j][i]
        sum_list.append(sum)
        sum = 0
    
    # loop through the list of sums to find the largest one.
    # since the list is chronological order according to the column order, the position of the
    #   largest number in the sum list corresponds to the column index.
    max_sum = sum_list[0]
    for i in range(len(sum_list)):
        if (sum_list[i] >= max_sum):
            max_sum = sum_list[i]

    # find the indices of the columns that have the largest sums.
    col_list = []
    for i in range(len(sum_list)):
        if (sum_list[i] == max_sum):
            col_list.append(i+1)

    results = [max_sum, col_list]
    
    return results

mtx = np.array([[11,11,11,1],[11,8,11,1],[11,11,11,1]])
print(f"The original matrix was:\n {mtx}")
results = biggest_sum(mtx)
max_sum = results[0]
col_num = results[1]

if (len(col_num) == 1):
    print(f"Column {col_num[0]} had the largest sum with {max_sum}.")
elif (len(col_num) == 2):
    print(f"Columns {col_num[0]} and {col_num[1]} had the largest sum with {max_sum}.")
else:
    print(f"Columns ", end = "")
    for i in range(len(col_num)-1):
        print(str(col_num[i]) + ", ", end = "")
    print(f"and {col_num[-1]} had the largest sum with {max_sum}.")

The original matrix was:
 [[11 11 11  1]
 [11  8 11  1]
 [11 11 11  1]]
Columns 1 and 3 had the largest sum with 33.


4. You are given a matrix of random numbers, you need to find the number of the column which has the biggest median of numbers.

In [64]:
import numpy as np
import statistics as stats

def biggest_median(mtx):
    # find the number of rows and columns.
    num_rows = mtx.shape[0]
    num_cols = mtx.shape[1]

    median = 0
    data_list = []
    median_list = []
    # loop through each column and record the values in a single column in a new data list.
    # use this data list as the data for the median() method from the statistics library, and
    #    add the calculated mean to a list of medians. 
    # clear the data list for the next column.
    for i in range(num_cols):
        for j in range(num_rows):
            data_list.append(mtx[j][i])
        median = stats.median(data_list)
        median_list.append(median)
        data_list = []
    
    # loop through the list of medians to find the largest one.
    max_median = median_list[0]
    for i in range(len(median_list)):
        if (median_list[i] >= max_median):
            max_median = median_list[i]

    col_list = []
    for i in range(len(median_list)):
        if (median_list[i] == max_median):
            col_list.append(i+1)

    results = [max_median, col_list]
    
    return results

mtx = np.array([[11,12,11,9],[11,8,10,3],[11,12,11,2]])
print(f"The original matrix was:\n {mtx}")
results = biggest_median(mtx)
max_median = results[0]
col_num = results[1]

if (len(col_num) == 1):
    print(f"Column {col_num[0]} had the largest median with {max_median}.")
elif (len(col_num) == 2):
    print(f"Columns {col_num[0]} and {col_num[1]} had the largest median with {max_median}.")
else:
    print(f"Columns ", end = "")
    for i in range(len(col_num)-1):
        print(str(col_num[i]) + ", ", end = "")
    print(f"and {col_num[-1]} had the largest median with {max_median}.")

The original matrix was:
 [[11 12 11  9]
 [11  8 10  3]
 [11 12 11  2]]
Column 2 had the largest median with 12.
