In [2]:
import numpy as np

1. You are given a matrix of random numbers, you need to output the matrix where odd rows are swapped with even rows in the original matrix.

In [3]:
def swap_rows(mtx):
    # find the number of rows and columns.
    num_rows = mtx.shape[0]
    # define a new matrix to put the swapped rows in. note that this isn't a numpy array, but a regular list.
    swapped_mtx = []
    # swap each odd row with the succeeding even row.
    for i in range(0,num_rows-1,2):
        swapped_mtx.append(mtx[i+1])
        swapped_mtx.append(mtx[i])
    # if there was an odd number of rows, the last row won't have another row to swap with and may get left off
    #   the final swapped matrix-- avoid this by adding the last row automatically when there's an odd amount of rows.
    if num_rows % 2 != 0:
        swapped_mtx.append(mtx[-1])
    # convert the list into a numpy array.
    s_mtx = np.array(swapped_mtx)
    return s_mtx

mtx = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f"Original matrix was:\n {mtx}\n")
print(f"Swapped matrix is:\n {swap_rows(mtx)}")


Original matrix was:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Swapped matrix is:
 [[ 4  5  6]
 [ 1  2  3]
 [10 11 12]
 [ 7  8  9]]
