In [440]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
import matplotlib.pyplot as plt
#from gym.envs.toy_text.frozen_lake import generate_random_map

In [441]:
env = gym.make("FrozenLake-v1", is_slippery=False, map_name="4x4")

In [442]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# EPSILON GREEDY STRATEGY
- When <font color = magenta>epsilon = 1</font>, it is 100% certain that the agent will __explore__ the environment.
> - As the agent learns more about the environment, <font color = magenta>epsilon</font> will decrease, and the agent will move from __exploring__ to __exploiting__.
> > - The rate at which <font color = magenta>epsilon</font> decays is the parameter we call <font color = cyan>exploration_decay_rate</font>.
> - The __discount_rate__ determines how much the agent cares about rewards in the future as opposed to right now.
> > - If gamma = 0, the agent will only learn about actions that produce an immediate reward.

In [443]:
num_episodes = 5000 # total number of episodes for the agent to play during training
max_steps_per_episode = 100 # maximum number of steps for agent to take within an episode

learning_rate = 0.4 # alpha in the eqn. larger alpha = quicker rewards
discount_rate = 0.9 # gamma in the eqn.

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 # a smaller decay rate results in the agent getting to rewards quicker.

### Code below is for running q-table.

In [444]:
'''rewards_all_episodes = []
y_points = []

while learning_rate < 1:

    # Q-learning algorithm
    for episode in range(num_episodes):
        state = env.reset() # reset game.

        done = False
        rewards_current_episode = 0 # game hasn't begun yet, so no rewards.

        for step in range(max_steps_per_episode):

            # Exploration-exploitation trade-off
            exploration_rate_threshold = random.uniform(0,1)
            # if the exploration_rate_threshold is greater than the exploration_rate, the agent will
            #   EXPLOIT the environment, and choose the action that has the highest value in the Q table
            #   for the current state. otherwise, the agent will explore the environment and sample 
            #   an action randomly.
            if exploration_rate_threshold > exploration_rate:
                action = np.argmax(q_table[state,:])
            else:
                action = env.action_space.sample()

            new_state, reward, done, info = env.step(action)

            # Update Q-table for Q(s,a)
            q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))

            state = new_state
            rewards_current_episode += reward

            if done == True:
                break

        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

        rewards_all_episodes.append(rewards_current_episode)

    # Calculate and print the average reward per thousand episodes
    rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
    count = 1000
    yp = []
    print("********Average reward per thousand episodes********\n")
    for r in rewards_per_thousand_episodes:
        print(count, ": ", str(sum(r/1000)))
        yp.append(sum(r/1000))
        count += 1000
    y_points.append(yp)
    print(learning_rate)
    learning_rate += 0.1

# Print updated Q table.
print("\n\n********Q-table********\n")
print(q_table)

# ypoints = np.array([yp_list])
#xpoints = np.array([1000,2000,3000,4000,5000])
x_points = np.array([1000,2000,3000,4000,5000])
learning_rate = 0.1
for i in range(len(y_points)):
    y_arr = np.array(y_points[i])
    plt.plot(x_points,y_arr, label=f"learning_rate = {learning_rate}")
    learning_rate = learning_rate + 0.1

plt.xlabel("Episodes")
plt.ylabel("Rewards")
plt.legend()
plt.show()'''

'rewards_all_episodes = []\ny_points = []\n\nwhile learning_rate < 1:\n\n    # Q-learning algorithm\n    for episode in range(num_episodes):\n        state = env.reset() # reset game.\n\n        done = False\n        rewards_current_episode = 0 # game hasn\'t begun yet, so no rewards.\n\n        for step in range(max_steps_per_episode):\n\n            # Exploration-exploitation trade-off\n            exploration_rate_threshold = random.uniform(0,1)\n            # if the exploration_rate_threshold is greater than the exploration_rate, the agent will\n            #   EXPLOIT the environment, and choose the action that has the highest value in the Q table\n            #   for the current state. otherwise, the agent will explore the environment and sample \n            #   an action randomly.\n            if exploration_rate_threshold > exploration_rate:\n                action = np.argmax(q_table[state,:])\n            else:\n                action = env.action_space.sample()\n\n         

In [445]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset() # reset game.

    done = False
    rewards_current_episode = 0 # game hasn't begun yet, so no rewards.

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        # if the exploration_rate_threshold is greater than the exploration_rate, the agent will
        #   EXPLOIT the environment, and choose the action that has the highest value in the Q table
        #   for the current state. otherwise, the agent will explore the environment and sample 
        #   an action randomly.
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)
print(learning_rate)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q table.
print("\n\n********Q-table********\n")
print(q_table)

0.4
********Average reward per thousand episodes********

1000 :  0.2660000000000002
2000 :  0.7340000000000005
3000 :  0.9140000000000007
4000 :  0.9620000000000007
5000 :  0.9800000000000008


********Q-table********

[[0.531441   0.59049    0.59049    0.531441  ]
 [0.531441   0.         0.6561     0.59049   ]
 [0.59049    0.729      0.59049    0.6561    ]
 [0.6561     0.         0.59047532 0.59048577]
 [0.59049    0.6561     0.         0.531441  ]
 [0.         0.         0.         0.        ]
 [0.         0.81       0.         0.6561    ]
 [0.         0.         0.         0.        ]
 [0.6561     0.         0.729      0.59049   ]
 [0.6561     0.81       0.81       0.        ]
 [0.729      0.9        0.         0.729     ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.81       0.9        0.729     ]
 [0.81       0.9        1.         0.81      ]
 [0.         0.         0.         0.        ]]


### Code below is for running visual display of the computer as it draws up the q-table.

In [446]:
'''rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)

        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole :(****")
                time.sleep(3)
            clear_output(wait=True)
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q table.
print("\n\n********Q-table********\n")
print(q_table)'''

'rewards_all_episodes = []\n\nfor episode in range(num_episodes):\n    state = env.reset()\n\n    done = False\n    rewards_current_episode = 0\n    print("*****EPISODE ", episode+1, "*****\n\n\n\n")\n    time.sleep(1)\n\n    for step in range(max_steps_per_episode):\n        exploration_rate_threshold = random.uniform(0,1)\n\n        clear_output(wait=True)\n        env.render()\n        time.sleep(0.3)\n        if exploration_rate_threshold > exploration_rate:\n            action = np.argmax(q_table[state,:])\n        else:\n            action = env.action_space.sample()\n\n        new_state, reward, done, info = env.step(action)\n\n        q_table[state, action] = q_table[state, action] * (1 - learning_rate) +             learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))\n\n        state = new_state\n        rewards_current_episode += reward\n\n        if done == True:\n            clear_output(wait=True)\n            env.render()\n            if reward == 1:\n

### Code below is for running visual display.

In [447]:
'''for episode in range(10):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole :(****")
                time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state

env.close()'''

'for episode in range(10):\n    state = env.reset()\n    done = False\n    print("*****EPISODE ", episode+1, "*****\n\n\n\n")\n    time.sleep(1)\n\n    for step in range(max_steps_per_episode):\n        clear_output(wait=True)\n        env.render()\n        time.sleep(0.3)\n\n        action = np.argmax(q_table[state,:])\n        new_state, reward, done, info = env.step(action)\n\n        if done:\n            clear_output(wait=True)\n            env.render()\n            if reward == 1:\n                print("****You reached the goal!****")\n                time.sleep(3)\n            else:\n                print("****You fell through a hole :(****")\n                time.sleep(3)\n            clear_output(wait=True)\n            break\n\n        state = new_state\n\nenv.close()'